replicaCount: 2

webapp:
  name: negin-neon-test
  group: negin-neon-test
  path: /
  tls:
    fqdn: negin-neon-test.k8s.ucar.edu
    fqdn2: ncar-neon-viz.k8s.ucar.edu
    secretName: incommon-account-key-neon
  container: 
    image: hub.k8s.ucar.edu/ncote/neon-app:2025-11-12.18.56
    port: 5006
    memory: 4G
    cpu: 2